### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by jfstephane** [DevoirEnGroupe/Mesajem#1]
[Updated group info](https://courses.codepath.org/courses/android_university/pages/group_project/02_update_group_info) in the Course Portal: Group Name + App Description. (1pt)

You MUST udpate your group infos, it's Required to be marked as complete

**Comment by windesigner12** [comment]
Group Info updated on the portal thank you!

**Comment by windesigner12** [comment]
Issue resolved, Group Name and info add on the Course Portal

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jules Frantz Stephane Loubeau ***@***.***>
Sent: Wednesday, September 7, 2022 9:40:03 AM
To: DevoirEnGroupe/Final ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DevoirEnGroupe/Final] Incomplete (Issue #1)


Updated group info<https://courses.codepath.org/courses/android_university/pages/group_project/02_update_group_info> in the Course Portal: Group Name + App Description. (1pt)

You MUST udpate your group infos, it's Required to be marked as complete
